In [3]:
import numpy as np

def get_numeric_input(prompt):
    while True:
        try:
            value = float(input(prompt))
            return value
        except ValueError:
            print("Masukkan harus berupa angka. Silakan coba lagi.")

def calculate_criteria_comparison_matrix(criteria_weights):
    criteria_count = len(criteria_weights)
    comparison_matrix = np.zeros((criteria_count, criteria_count))

    for i in range(criteria_count):
        for j in range(i + 1, criteria_count):
            comparison_matrix[i, j] = criteria_weights[i] / criteria_weights[j]
            comparison_matrix[j, i] = criteria_weights[j] / criteria_weights[i]

    return comparison_matrix

def calculate_ahp(comparison_matrix):
    # Step 1: Hitung Jumlah Baris Matriks
    row_sums = comparison_matrix.sum(axis=1)

    # Step 2: Normalisasi Matriks
    normalized_matrix = comparison_matrix / row_sums[:, np.newaxis]

    # Step 3: Hitung Vektor Eigen
    eigen_vector = normalized_matrix.mean(axis=1)

    # Step 4: Hitung Nilai Eigen
    eigen_value = eigen_vector.mean()

    # Step 5: Hitung Konsistensi (Opsional)
    n = comparison_matrix.shape[0]
    weighted_sum = np.dot(comparison_matrix, eigen_vector)
    lambda_max = np.sum(weighted_sum / eigen_vector) / n
    consistency_index = (lambda_max - n) / (n - 1)
    random_index = {3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45}
    consistency_ratio = consistency_index / random_index[n]

    # Step 6: Hitung Vektor Prioritas Global
    global_priority_vector = eigen_vector / eigen_vector.sum()

    return eigen_value, global_priority_vector, consistency_ratio

def determine_weights(eigen_value, criteria_count):
    weights = np.full(criteria_count, eigen_value ** (1 / criteria_count))
    normalized_weights = weights / sum(weights)
    return normalized_weights

# Menentukan bobot kriteria dari pengguna
criteria_weights = [0.1888, 0.0417, 0.2938, 0.1529, 0.3228]

# Menghitung matriks perbandingan kriteria
comparison_matrix = calculate_criteria_comparison_matrix(criteria_weights)

# Menghitung AHP
eigen_value, global_priority_vector, consistency_ratio = calculate_ahp(comparison_matrix)

# Menampilkan hasil AHP
print("\nMatriks Perbandingan Kriteria:")
print(comparison_matrix)
print("\nHasil Analisis AHP:")
print(f"Nilai Eigen: {eigen_value}")
print(f"Vektor Prioritas Global: {global_priority_vector}")
print(f"Rasio Konsistensi (Opsional): {consistency_ratio}")

# Menentukan bobot
weights = determine_weights(eigen_value, len(criteria_weights))

# Menampilkan bobot
print("\nBobot Kriteria:")
print(weights)



Matriks Perbandingan Kriteria:
[[0.         4.52757794 0.64261402 1.23479398 0.58488228]
 [0.22086864 0.         0.14193329 0.27272727 0.12918216]
 [1.55614407 7.04556355 0.         1.92151733 0.91016109]
 [0.80985169 3.66666667 0.52042206 0.         0.47366791]
 [1.70974576 7.74100719 1.0987066  2.11118378 0.        ]]

Hasil Analisis AHP:
Nilai Eigen: 0.2
Vektor Prioritas Global: [0.2 0.2 0.2 0.2 0.2]
Rasio Konsistensi (Opsional): 0.5499650574681881

Bobot Kriteria:
[0.2 0.2 0.2 0.2 0.2]


In [4]:
criteria_comparison_matrix = np.array([
    [1, 3, 0.2, 0.2, 3],
    [1/3, 1, 0.14, 1/3, 1/3],
    [5, 7, 1, 5, 0.2],
    [5, 3, 0.2, 1, 0.2],
    [1/3, 3, 5, 5, 1]
])


In [5]:
row_sums = criteria_comparison_matrix.sum(axis=1)
normalized_matrix = criteria_comparison_matrix / row_sums[:, np.newaxis]


In [6]:
weights = np.array([0.1888, 0.0417, 0.2938, 0.1529, 0.3228])
weighted_normalized_matrix = normalized_matrix * weights


In [7]:
alternative_scores = weighted_normalized_matrix.sum(axis=1)


In [8]:
import numpy as np

# Define the pairwise comparison matrix for the criteria
criteria_comparison_matrix = np.array([
    [1, 3, 0.2, 0.2, 3],
    [1/3, 1, 0.14, 1/3, 1/3],
    [5, 7, 1, 5, 0.2],
    [5, 3, 0.2, 1, 0.2],
    [1/3, 3, 5, 5, 1]
])

# Calculate the normalized matrix
row_sums = criteria_comparison_matrix.sum(axis=1)
normalized_matrix = criteria_comparison_matrix / row_sums[:, np.newaxis]

# Define the weights for the criteria
weights = np.array([0.1888, 0.0417, 0.2938, 0.1529, 0.3228])

# Calculate the weighted normalized matrix
weighted_normalized_matrix = normalized_matrix * weights

# Calculate the alternative scores
alternative_scores = weighted_normalized_matrix.sum(axis=1)

# Display the results
print("\nMatriks Perbandingan Kriteria:")
print(criteria_comparison_matrix)
print("\nMatriks Normalisasi:")
print(normalized_matrix)
print("\nBobot Kriteria:")
print(weights)
print("\nMatriks Normalisasi Terbobot:")
print(weighted_normalized_matrix)
print("\nNilai Alternatif terhadap Kriteria:")
print(alternative_scores)



Matriks Perbandingan Kriteria:
[[1.         3.         0.2        0.2        3.        ]
 [0.33333333 1.         0.14       0.33333333 0.33333333]
 [5.         7.         1.         5.         0.2       ]
 [5.         3.         0.2        1.         0.2       ]
 [0.33333333 3.         5.         5.         1.        ]]

Matriks Normalisasi:
[[0.13513514 0.40540541 0.02702703 0.02702703 0.40540541]
 [0.15576324 0.46728972 0.06542056 0.15576324 0.15576324]
 [0.27472527 0.38461538 0.05494505 0.27472527 0.01098901]
 [0.53191489 0.31914894 0.0212766  0.10638298 0.0212766 ]
 [0.02325581 0.20930233 0.34883721 0.34883721 0.06976744]]

Bobot Kriteria:
[0.1888 0.0417 0.2938 0.1529 0.3228]

Matriks Normalisasi Terbobot:
[[0.02551351 0.01690541 0.00794054 0.00413243 0.13086486]
 [0.0294081  0.01948598 0.01922056 0.0238162  0.05028037]
 [0.05186813 0.01603846 0.01614286 0.04200549 0.00354725]
 [0.10042553 0.01330851 0.00625106 0.01626596 0.00686809]
 [0.0043907  0.00872791 0.10248837 0.05333721 0

In [ ]:
#numb3

In [9]:
import numpy as np

# Define the matrix of normalized eigenvalues
normalized_eigenvalues_matrix = np.array([
    [0.0857, 0.1765, 0.0306, 0.0173, 0.6338],
    [0.0286, 0.0588, 0.0218, 0.0289, 0.0704],
    [0.4286, 0.4118, 0.1528, 0.4335, 0.0423],
    [0.4286, 0.1765, 0.0306, 0.0867, 0.0423],
    [0.0286, 0.1765, 0.7642, 0.4335, 0.2113]
])

# Define the weights for the criteria
weights = np.array([0.1888, 0.0417, 0.2938, 0.1529, 0.3228])

# Calculate the relative scores
relative_scores = np.dot(normalized_eigenvalues_matrix, weights)

# Calculate the consistency ratio
consistency_ratio = np.sum(relative_scores) / np.sum(weights)

# Display the results
print("\nMatriks Nilai Kriteria (Normalisasi Nilai Eigen):")
print(normalized_eigenvalues_matrix)
print("\nBobot Kriteria:")
print(weights)
print("\nSkor Relatif:")
print(relative_scores)
print("\nKonsistensi Ratio:")
print(consistency_ratio)



Matriks Nilai Kriteria (Normalisasi Nilai Eigen):
[[0.0857 0.1765 0.0306 0.0173 0.6338]
 [0.0286 0.0588 0.0218 0.0289 0.0704]
 [0.4286 0.4118 0.1528 0.4335 0.0423]
 [0.4286 0.1765 0.0306 0.0867 0.0423]
 [0.0286 0.1765 0.7642 0.4335 0.2113]]

Bobot Kriteria:
[0.1888 0.0417 0.2938 0.1529 0.3228]

Skor Relatif:
[0.2397663  0.04140041 0.22292097 0.12418088 0.37177148]

Konsistensi Ratio:
1.00004004


In [10]:
import numpy as np

# Define the pairwise comparison matrix for alternative locations based on Biaya Tanah
comparison_matrix_biaya_tanah = np.array([
    [1, 0.2, 0.17],
    [5, 1, 3],
    [6, 0.33, 1]
])

# Calculate the normalized matrix
row_sums_biaya_tanah = comparison_matrix_biaya_tanah.sum(axis=1)
normalized_matrix_biaya_tanah = comparison_matrix_biaya_tanah / row_sums_biaya_tanah[:, np.newaxis]

# Calculate the priority vector
priority_vector_biaya_tanah = normalized_matrix_biaya_tanah.mean(axis=1)

# Display the results
print("\nPerbandingan Alternatif Kriteria Biaya Tanah:")
print(comparison_matrix_biaya_tanah)
print("\nMatriks Normalisasi:")
print(normalized_matrix_biaya_tanah)
print("\nPriority Vector:")
print(priority_vector_biaya_tanah)



Perbandingan Alternatif Kriteria Biaya Tanah:
[[1.   0.2  0.17]
 [5.   1.   3.  ]
 [6.   0.33 1.  ]]

Matriks Normalisasi:
[[0.72992701 0.1459854  0.12408759]
 [0.55555556 0.11111111 0.33333333]
 [0.81855389 0.04502046 0.13642565]]

Priority Vector:
[0.33333333 0.33333333 0.33333333]


In [11]:
import numpy as np

# Define the pairwise comparison matrix for alternative locations based on Aksebilitas
comparison_matrix_aksebilitas = np.array([
    [1, 0.33, 0.14],
    [3, 1, 5],
    [7, 0.2, 1]
])

# Calculate the normalized matrix
row_sums_aksebilitas = comparison_matrix_aksebilitas.sum(axis=1)
normalized_matrix_aksebilitas = comparison_matrix_aksebilitas / row_sums_aksebilitas[:, np.newaxis]

# Calculate the sum of weights
sum_of_weights_aksebilitas = normalized_matrix_aksebilitas.sum(axis=0)

# Display the results
print("\nPerbandingan Alternatif Kriteria Aksebilitas:")
print(comparison_matrix_aksebilitas)
print("\nMatriks Normalisasi:")
print(normalized_matrix_aksebilitas)
print("\nJumlah Bobot Pada Alternatif Kriteria Aksebilitas:")
print(sum_of_weights_aksebilitas)



Perbandingan Alternatif Kriteria Aksebilitas:
[[1.   0.33 0.14]
 [3.   1.   5.  ]
 [7.   0.2  1.  ]]

Matriks Normalisasi:
[[0.68027211 0.2244898  0.0952381 ]
 [0.33333333 0.11111111 0.55555556]
 [0.85365854 0.02439024 0.12195122]]

Jumlah Bobot Pada Alternatif Kriteria Aksebilitas:
[1.86726398 0.35999115 0.77274487]


In [12]:
import numpy as np

# Define the normalized matrix for alternative locations based on Aksebilitas
normalized_matrix_aksebilitas = np.array([
    [0.0909, 0.2174, 0.02333],
    [0.2727, 0.6522, 0.814],
    [0.6364, 0.3104, 0.1628]
])

# Calculate the sum of weights
sum_of_weights_aksebilitas = normalized_matrix_aksebilitas.sum(axis=0)

# Calculate the priority vector
priority_vector_aksebilitas = sum_of_weights_aksebilitas / sum(sum_of_weights_aksebilitas)

# Display the results
print("\nMatriks Nilai Alternatif Dalam Kriteria Aksebilitas (Normalisasi Nilai Eigen):")
print(normalized_matrix_aksebilitas)
print("\nJumlah Bobot Pada Alternatif Kriteria Aksebilitas:")
print(sum_of_weights_aksebilitas)
print("\nPrioritas Vector:")
print(priority_vector_aksebilitas)



Matriks Nilai Alternatif Dalam Kriteria Aksebilitas (Normalisasi Nilai Eigen):
[[0.0909  0.2174  0.02333]
 [0.2727  0.6522  0.814  ]
 [0.6364  0.3104  0.1628 ]]

Jumlah Bobot Pada Alternatif Kriteria Aksebilitas:
[1.      1.18    1.00013]

Prioritas Vector:
[0.31445255 0.37105401 0.31449343]


In [13]:
import numpy as np

# Define the normalized matrix for alternative locations based on Biaya Tenaga Kerja
normalized_matrix_biaya_tenaga_kerja = np.array([
    [0.7317, 0.4286, 0.814],
    [0.122, 0.0714, 0.0233],
    [0.1463, 0.5, 0.1628]
])

# Calculate the sum of weights
sum_of_weights_biaya_tenaga_kerja = normalized_matrix_biaya_tenaga_kerja.sum(axis=0)

# Calculate the priority vector
priority_vector_biaya_tenaga_kerja = sum_of_weights_biaya_tenaga_kerja / sum(sum_of_weights_biaya_tenaga_kerja)

# Display the results
print("\nMatriks Nilai Alternatif Dalam Kriteria Biaya Tenaga Kerja (Normalisasi Nilai Eigen):")
print(normalized_matrix_biaya_tenaga_kerja)
print("\nJumlah Bobot Pada Alternatif Kriteria Biaya Tenaga Kerja:")
print(sum_of_weights_biaya_tenaga_kerja)
print("\nPrioritas Vector:")
print(priority_vector_biaya_tenaga_kerja)



Matriks Nilai Alternatif Dalam Kriteria Biaya Tenaga Kerja (Normalisasi Nilai Eigen):
[[0.7317 0.4286 0.814 ]
 [0.122  0.0714 0.0233]
 [0.1463 0.5    0.1628]]

Jumlah Bobot Pada Alternatif Kriteria Biaya Tenaga Kerja:
[1.     1.     1.0001]

Prioritas Vector:
[0.33332222 0.33332222 0.33335555]


In [14]:
import numpy as np

# Define the pairwise comparison matrix for alternative locations based on Infrastruktur
comparison_matrix_infrastruktur = np.array([
    [1, 0.14, 3],
    [7, 1, 3],
    [0.33, 0.33, 1]
])

# Calculate the normalized matrix
row_sums_infrastruktur = comparison_matrix_infrastruktur.sum(axis=1)
normalized_matrix_infrastruktur = comparison_matrix_infrastruktur / row_sums_infrastruktur[:, np.newaxis]

# Calculate the sum of weights
sum_of_weights_infrastruktur = normalized_matrix_infrastruktur.sum(axis=0)

# Calculate the priority vector
priority_vector_infrastruktur = sum_of_weights_infrastruktur / sum(sum_of_weights_infrastruktur)

# Display the results
print("\nMatriks Perbandingan Alternatif Pada Kriteria Infrastruktur:")
print(comparison_matrix_infrastruktur)
print("\nMatriks Normalisasi:")
print(normalized_matrix_infrastruktur)
print("\nJumlah Bobot Pada Alternatif Kriteria Infrastruktur:")
print(sum_of_weights_infrastruktur)
print("\nPrioritas Vector:")
print(priority_vector_infrastruktur)



Matriks Perbandingan Alternatif Pada Kriteria Infrastruktur:
[[1.   0.14 3.  ]
 [7.   1.   3.  ]
 [0.33 0.33 1.  ]]

Matriks Normalisasi:
[[0.24154589 0.03381643 0.72463768]
 [0.63636364 0.09090909 0.27272727]
 [0.19879518 0.19879518 0.60240964]]

Jumlah Bobot Pada Alternatif Kriteria Infrastruktur:
[1.07670471 0.3235207  1.59977459]

Prioritas Vector:
[0.35890157 0.10784023 0.5332582 ]


In [15]:
import numpy as np

# Define the pairwise comparison matrix for alternative locations based on Dampak Lingkungan
comparison_matrix_dampak_lingkungan = np.array([
    [1, 7, 0.14],
    [0.14, 1, 0.11],
    [7, 9, 1]
])

# Calculate the normalized matrix
row_sums_dampak_lingkungan = comparison_matrix_dampak_lingkungan.sum(axis=1)
normalized_matrix_dampak_lingkungan = comparison_matrix_dampak_lingkungan / row_sums_dampak_lingkungan[:, np.newaxis]

# Calculate the sum of weights
sum_of_weights_dampak_lingkungan = normalized_matrix_dampak_lingkungan.sum(axis=0)

# Calculate the priority vector
priority_vector_dampak_lingkungan = sum_of_weights_dampak_lingkungan / sum(sum_of_weights_dampak_lingkungan)

# Display the results
print("\nMatriks Perbandingan Alternatif Pada Kriteria Dampak Lingkungan:")
print(comparison_matrix_dampak_lingkungan)
print("\nMatriks Normalisasi:")
print(normalized_matrix_dampak_lingkungan)
print("\nJumlah Bobot Pada Alternatif Kriteria Dampak Lingkungan:")
print(sum_of_weights_dampak_lingkungan)
print("\nPrioritas Vector:")
print(priority_vector_dampak_lingkungan)



Matriks Perbandingan Alternatif Pada Kriteria Dampak Lingkungan:
[[1.   7.   0.14]
 [0.14 1.   0.11]
 [7.   9.   1.  ]]

Matriks Normalisasi:
[[0.12285012 0.85995086 0.01719902]
 [0.112      0.8        0.088     ]
 [0.41176471 0.52941176 0.05882353]]

Jumlah Bobot Pada Alternatif Kriteria Dampak Lingkungan:
[0.64661483 2.18936262 0.16402255]

Prioritas Vector:
[0.21553828 0.72978754 0.05467418]


In [16]:
import numpy as np

# Define the normalized matrix for alternative locations based on Dampak Lingkungan
normalized_matrix_dampak_lingkungan = np.array([
    [0.1228, 0.4118, 0.1139],
    [0.0175, 0.0588, 0.0886],
    [0.8596, 0.5294, 0.7975]
])

# Calculate the sum of weights
sum_of_weights_dampak_lingkungan = normalized_matrix_dampak_lingkungan.sum(axis=0)

# Calculate the priority vector
priority_vector_dampak_lingkungan = sum_of_weights_dampak_lingkungan / sum(sum_of_weights_dampak_lingkungan)

# Display the results
print("\nMatriks Nilai Alternatif Dalam Kriteria Dampak Lingkungan (Normalisasi Nilai Eigen):")
print(normalized_matrix_dampak_lingkungan)
print("\nJumlah Bobot Pada Alternatif Kriteria Dampak Lingkungan:")
print(sum_of_weights_dampak_lingkungan)
print("\nPrioritas Vector:")
print(priority_vector_dampak_lingkungan)



Matriks Nilai Alternatif Dalam Kriteria Dampak Lingkungan (Normalisasi Nilai Eigen):
[[0.1228 0.4118 0.1139]
 [0.0175 0.0588 0.0886]
 [0.8596 0.5294 0.7975]]

Jumlah Bobot Pada Alternatif Kriteria Dampak Lingkungan:
[0.9999 1.     1.    ]

Prioritas Vector:
[0.33331111 0.33334444 0.33334444]


In [ ]:
#Potential Violence

In [17]:
import numpy as np

# Define bobot dan prioritas untuk setiap kriteria
kriteria_bobot = np.array([0.1888, 0.0417, 0.2938, 0.1529, 0.3228])
kriteria_prioritas = np.array([3, 5, 2, 4, 1])

# Menghitung skor akhir untuk setiap lokasi
def hitung_skor_akhir(bobot, prioritas):
    skor_lokasi = np.dot(bobot, prioritas)
    return skor_lokasi

# Hitung skor akhir untuk setiap lokasi
skor_lokasi_A = hitung_skor_akhir(kriteria_bobot, kriteria_prioritas)
skor_lokasi_B = hitung_skor_akhir(kriteria_bobot, kriteria_prioritas)

# Menampilkan hasil
print("Skor Akhir untuk Lokasi A:", skor_lokasi_A)
print("Skor Akhir untuk Lokasi B:", skor_lokasi_B)


Skor Akhir untuk Lokasi A: 2.2969
Skor Akhir untuk Lokasi B: 2.2969


In [18]:
import numpy as np

# Mendefinisikan bobot dan prioritas untuk setiap kriteria
kriteria_bobot = np.array([0.1888, 0.0417, 0.2938, 0.1529, 0.3228])
kriteria_prioritas = np.array([3, 5, 2, 4, 1])

# Mendefinisikan bobot dan prioritas untuk setiap kriteria (lokasi A)
lokasi_A_bobot = np.array([0.1888, 0.0417, 0.2938, 0.1529, 0.3228])
lokasi_A_prioritas = np.array([3, 5, 2, 4, 1])

# Mendefinisikan bobot dan prioritas untuk setiap kriteria (lokasi B)
lokasi_B_bobot = np.array([0.1888, 0.0417, 0.2938, 0.1529, 0.3228])
lokasi_B_prioritas = np.array([3, 5, 2, 4, 1])

# Fungsi untuk menghitung skor akhir
def hitung_skor_akhir(bobot, prioritas):
    skor_lokasi = np.dot(bobot, prioritas)
    return skor_lokasi

# Menghitung skor akhir untuk setiap lokasi
skor_lokasi_A = hitung_skor_akhir(lokasi_A_bobot, lokasi_A_prioritas)
skor_lokasi_B = hitung_skor_akhir(lokasi_B_bobot, lokasi_B_prioritas)

# Menampilkan hasil
print("Skor Akhir untuk Lokasi A:", skor_lokasi_A)
print("Skor Akhir untuk Lokasi B:", skor_lokasi_B)


Skor Akhir untuk Lokasi A: 2.2969
Skor Akhir untuk Lokasi B: 2.2969


In [19]:
import numpy as np

# Mendefinisikan bobot dan prioritas untuk setiap kriteria
kriteria_bobot = np.array([0.1888, 0.0417, 0.2938, 0.1529, 0.3228])
kriteria_prioritas = np.array([3, 5, 2, 4, 1])

# Mendefinisikan bobot dan prioritas untuk setiap lokasi
lokasi_A_bobot = np.array([0.3166, 0.2749, 0.4085])
lokasi_A_prioritas = np.array([2, 3, 1])

# Fungsi untuk menghitung skor akhir
def hitung_skor_akhir(bobot_kriteria, prioritas_kriteria, bobot_lokasi, prioritas_lokasi):
    skor_lokasi = np.dot(bobot_kriteria, prioritas_kriteria) * np.dot(bobot_lokasi, prioritas_lokasi)
    return skor_lokasi

# Menghitung skor akhir untuk setiap lokasi
skor_lokasi_A = hitung_skor_akhir(kriteria_bobot, kriteria_prioritas, lokasi_A_bobot, lokasi_A_prioritas)

# Menampilkan hasil
print("Skor Akhir untuk Lokasi A:", skor_lokasi_A)


Skor Akhir untuk Lokasi A: 4.28693416


In [ ]:
#StartHere

In [20]:
import numpy as np

# Mendefinisikan bobot dan prioritas untuk setiap kriteria
kriteria_bobot = np.array([0.1888, 0.0417, 0.2938, 0.1529, 0.3228])
kriteria_prioritas = np.array([3, 5, 2, 4, 1])

# Mendefinisikan bobot dan prioritas untuk setiap lokasi
lokasi_bobot = np.array([0.3166, 0.2749, 0.4085])
lokasi_prioritas = np.array([2, 3, 1])

# Fungsi untuk menghitung skor akhir
def hitung_skor_akhir(bobot_kriteria, prioritas_kriteria, bobot_lokasi, prioritas_lokasi):
    skor_lokasi = np.dot(bobot_kriteria, prioritas_kriteria) * np.dot(bobot_lokasi, prioritas_lokasi)
    return skor_lokasi

# Menghitung skor akhir untuk setiap lokasi
skor_lokasi = hitung_skor_akhir(kriteria_bobot, kriteria_prioritas, lokasi_bobot, lokasi_prioritas)

# Menampilkan hasil
print("Skor Akhir untuk Lokasi:", skor_lokasi)


Skor Akhir untuk Lokasi: 4.28693416


In [21]:
import numpy as np

# Mendefinisikan bobot dan prioritas untuk setiap kriteria
kriteria_bobot = np.array([2.198611111, 1.909027778, 2.836805556])
kriteria_prioritas = np.array([2, 3, 1])

# Mendefinisikan bobot dan prioritas untuk setiap lokasi
lokasi_bobot = np.array([2.198611111, 1.909027778, 2.836805556])
lokasi_prioritas = np.array([2, 3, 1])

# Fungsi untuk menghitung skor akhir
def hitung_skor_akhir(bobot_kriteria, prioritas_kriteria, bobot_lokasi, prioritas_lokasi):
    skor_lokasi = np.dot(bobot_kriteria, prioritas_kriteria) * np.dot(bobot_lokasi, prioritas_lokasi)
    return skor_lokasi

# Menghitung skor akhir untuk setiap lokasi
skor_lokasi = hitung_skor_akhir(kriteria_bobot, kriteria_prioritas, lokasi_bobot, lokasi_prioritas)

# Menampilkan hasil
print("Skor Akhir untuk Lokasi:", skor_lokasi)


Skor Akhir untuk Lokasi: 167.99040125760985


In [ ]:
#EndHere

In [ ]:
#StartHere

In [22]:
import numpy as np

# Mendefinisikan bobot dan prioritas untuk setiap kriteria
kriteria_bobot = np.array([0.1888, 0.0417, 0.2938, 0.1529, 0.3228])
kriteria_prioritas = np.array([3, 5, 2, 4, 1])

# Mendefinisikan skor akhir untuk setiap lokasi
skor_lokasi_A = 10  # Ganti dengan skor akhir yang telah dihitung untuk Lokasi A
skor_lokasi_B = 15  # Ganti dengan skor akhir yang telah dihitung untuk Lokasi B
skor_lokasi_C = 8   # Ganti dengan skor akhir yang telah dihitung untuk Lokasi C

# Menghitung total skor akhir dari semua lokasi
total_skor_akhir = skor_lokasi_A + skor_lokasi_B + skor_lokasi_C

# Menghitung bobot untuk masing-masing lokasi
bobot_lokasi_A = skor_lokasi_A / total_skor_akhir
bobot_lokasi_B = skor_lokasi_B / total_skor_akhir
bobot_lokasi_C = skor_lokasi_C / total_skor_akhir

# Menampilkan hasil
print("Bobot Lokasi A:", bobot_lokasi_A)
print("Bobot Lokasi B:", bobot_lokasi_B)
print("Bobot Lokasi C:", bobot_lokasi_C)


Bobot Lokasi A: 0.30303030303030304
Bobot Lokasi B: 0.45454545454545453
Bobot Lokasi C: 0.24242424242424243
